# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analyze_h5_file.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_H5Analyzer(object):
    def setupUi(self, H5Analyzer):
        H5Analyzer.setObjectName("H5Analyzer")
        H5Analyzer.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(H5Analyzer)
        self.centralwidget.setObjectName("centralwidget")
        self.openFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.openFileButton.setGeometry(QtCore.QRect(10, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.openFileButton.setFont(font)
        self.openFileButton.setObjectName("openFileButton")
        self.windowInput = QtWidgets.QLineEdit(self.centralwidget)
        self.windowInput.setGeometry(QtCore.QRect(258, 40, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.windowInput.setFont(font)
        self.windowInput.setMaxLength(5)
        self.windowInput.setAlignment(QtCore.Qt.AlignCenter)
        self.windowInput.setObjectName("windowInput")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(228, 10, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(328, 0, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.maxRecordingThreshInput = QtWidgets.QLineEdit(self.centralwidget)
        self.maxRecordingThreshInput.setGeometry(QtCore.QRect(338, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.maxRecordingThreshInput.setFont(font)
        self.maxRecordingThreshInput.setMaxLength(6)
        self.maxRecordingThreshInput.setAlignment(QtCore.Qt.AlignCenter)
        self.maxRecordingThreshInput.setObjectName("maxRecordingThreshInput")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(428, 0, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.minRecordingThreshInput = QtWidgets.QLineEdit(self.centralwidget)
        self.minRecordingThreshInput.setGeometry(QtCore.QRect(440, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minRecordingThreshInput.setFont(font)
        self.minRecordingThreshInput.setMaxLength(6)
        self.minRecordingThreshInput.setAlignment(QtCore.Qt.AlignCenter)
        self.minRecordingThreshInput.setObjectName("minRecordingThreshInput")
        self.fileLoadDisplay = QtWidgets.QLabel(self.centralwidget)
        self.fileLoadDisplay.setGeometry(QtCore.QRect(120, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fileLoadDisplay.setFont(font)
        self.fileLoadDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.fileLoadDisplay.setObjectName("fileLoadDisplay")
        self.getInterestingChannelsButton = QtWidgets.QPushButton(self.centralwidget)
        self.getInterestingChannelsButton.setGeometry(QtCore.QRect(10, 80, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.getInterestingChannelsButton.setFont(font)
        self.getInterestingChannelsButton.setObjectName("getInterestingChannelsButton")
        self.analysisProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.analysisProgressBar.setGeometry(QtCore.QRect(10, 120, 251, 31))
        self.analysisProgressBar.setProperty("value", 24)
        self.analysisProgressBar.setObjectName("analysisProgressBar")
        self.plotChannelWidget = MplWidget(self.centralwidget)
        self.plotChannelWidget.setGeometry(QtCore.QRect(10, 220, 521, 481))
        self.plotChannelWidget.setObjectName("plotChannelWidget")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 150, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.channelSelectInput = QtWidgets.QLineEdit(self.centralwidget)
        self.channelSelectInput.setGeometry(QtCore.QRect(10, 180, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.channelSelectInput.setFont(font)
        self.channelSelectInput.setMaxLength(5)
        self.channelSelectInput.setAlignment(QtCore.Qt.AlignCenter)
        self.channelSelectInput.setObjectName("channelSelectInput")
        self.interestingChannelDisplay = QtWidgets.QTextEdit(self.centralwidget)
        self.interestingChannelDisplay.setGeometry(QtCore.QRect(270, 100, 261, 51))
        self.interestingChannelDisplay.setReadOnly(True)
        self.interestingChannelDisplay.setObjectName("interestingChannelDisplay")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(270, 80, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.FileNameDisplay = QtWidgets.QTextEdit(self.centralwidget)
        self.FileNameDisplay.setGeometry(QtCore.QRect(10, 40, 231, 31))
        self.FileNameDisplay.setReadOnly(True)
        self.FileNameDisplay.setObjectName("FileNameDisplay")
        self.plotChannelButton = QtWidgets.QPushButton(self.centralwidget)
        self.plotChannelButton.setGeometry(QtCore.QRect(130, 160, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plotChannelButton.setFont(font)
        self.plotChannelButton.setObjectName("plotChannelButton")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(570, 0, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.minPeakSeparationInput = QtWidgets.QLineEdit(self.centralwidget)
        self.minPeakSeparationInput.setGeometry(QtCore.QRect(570, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minPeakSeparationInput.setFont(font)
        self.minPeakSeparationInput.setMaxLength(6)
        self.minPeakSeparationInput.setAlignment(QtCore.Qt.AlignCenter)
        self.minPeakSeparationInput.setObjectName("minPeakSeparationInput")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(670, 0, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.minStdThreshInput = QtWidgets.QLineEdit(self.centralwidget)
        self.minStdThreshInput.setGeometry(QtCore.QRect(670, 40, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minStdThreshInput.setFont(font)
        self.minStdThreshInput.setMaxLength(6)
        self.minStdThreshInput.setAlignment(QtCore.Qt.AlignCenter)
        self.minStdThreshInput.setObjectName("minStdThreshInput")
        self.analyzeChannelButton = QtWidgets.QPushButton(self.centralwidget)
        self.analyzeChannelButton.setGeometry(QtCore.QRect(760, 30, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.analyzeChannelButton.setFont(font)
        self.analyzeChannelButton.setObjectName("analyzeChannelButton")
        self.saveAnalyzedDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveAnalyzedDataButton.setGeometry(QtCore.QRect(880, 30, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.saveAnalyzedDataButton.setFont(font)
        self.saveAnalyzedDataButton.setObjectName("saveAnalyzedDataButton")
        self.plotChoiceBox = QtWidgets.QComboBox(self.centralwidget)
        self.plotChoiceBox.setGeometry(QtCore.QRect(540, 370, 211, 31))
        self.plotChoiceBox.setObjectName("plotChoiceBox")
        self.plotChoiceBox.addItem("")
        self.plotChoiceBox.addItem("")
        self.plotChoiceBox.addItem("")
        self.plotChoiceBox.addItem("")
        self.plotChoiceBox.addItem("")
        self.plotChoiceBox.addItem("")
        self.plotChoiceButton = QtWidgets.QPushButton(self.centralwidget)
        self.plotChoiceButton.setGeometry(QtCore.QRect(910, 370, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plotChoiceButton.setFont(font)
        self.plotChoiceButton.setObjectName("plotChoiceButton")
        self.plotParametersWidget = MplWidget(self.centralwidget)
        self.plotParametersWidget.setGeometry(QtCore.QRect(540, 400, 471, 301))
        self.plotParametersWidget.setObjectName("plotParametersWidget")
        self.saveDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveDataButton.setGeometry(QtCore.QRect(250, 160, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.saveDataButton.setFont(font)
        self.saveDataButton.setObjectName("saveDataButton")
        self.plotAnalyzedWidget = MplWidget(self.centralwidget)
        self.plotAnalyzedWidget.setGeometry(QtCore.QRect(540, 80, 471, 291))
        self.plotAnalyzedWidget.setObjectName("plotAnalyzedWidget")
        self.cellTypeDisplay = QtWidgets.QTextEdit(self.centralwidget)
        self.cellTypeDisplay.setGeometry(QtCore.QRect(380, 160, 151, 51))
        self.cellTypeDisplay.setReadOnly(True)
        self.cellTypeDisplay.setObjectName("cellTypeDisplay")
        H5Analyzer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(H5Analyzer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 25))
        self.menubar.setObjectName("menubar")
        H5Analyzer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(H5Analyzer)
        self.statusbar.setObjectName("statusbar")
        H5Analyzer.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(H5Analyzer)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(H5Analyzer)
        self.actionSave.setObjectName("actionSave")

        self.retranslateUi(H5Analyzer)
        QtCore.QMetaObject.connectSlotsByName(H5Analyzer)

    def retranslateUi(self, H5Analyzer):
        _translate = QtCore.QCoreApplication.translate
        H5Analyzer.setWindowTitle(_translate("H5Analyzer", "MainWindow"))
        self.openFileButton.setText(_translate("H5Analyzer", "Open h5 File"))
        self.windowInput.setText(_translate("H5Analyzer", "20"))
        self.label_2.setText(_translate("H5Analyzer", "Window Size"))
        self.label_3.setText(_translate("H5Analyzer", "Max Recording Threshold/uV"))
        self.maxRecordingThreshInput.setText(_translate("H5Analyzer", "60000"))
        self.label_4.setText(_translate("H5Analyzer", "Min Recording Threshold/uV"))
        self.minRecordingThreshInput.setText(_translate("H5Analyzer", "-60000"))
        self.fileLoadDisplay.setText(_translate("H5Analyzer", "Select File..."))
        self.getInterestingChannelsButton.setText(_translate("H5Analyzer", "Get Interesting Channels!"))
        self.label_5.setText(_translate("H5Analyzer", "Plot Channel ID"))
        self.channelSelectInput.setText(_translate("H5Analyzer", "20"))
        self.label_6.setText(_translate("H5Analyzer", "Interesting Channel IDs"))
        self.plotChannelButton.setText(_translate("H5Analyzer", "Plot!"))
        self.label_7.setText(_translate("H5Analyzer", "Min Peak Separation/s"))
        self.minPeakSeparationInput.setText(_translate("H5Analyzer", "0.4"))
        self.label_8.setText(_translate("H5Analyzer", "Min Std Threshold"))
        self.minStdThreshInput.setText(_translate("H5Analyzer", "10"))
        self.analyzeChannelButton.setText(_translate("H5Analyzer", "Analyze!"))
        self.saveAnalyzedDataButton.setText(_translate("H5Analyzer", "Save Analyzed\n"
" Data"))
        self.plotChoiceBox.setItemText(0, _translate("H5Analyzer", "Start to Max Amplitude"))
        self.plotChoiceBox.setItemText(1, _translate("H5Analyzer", "Min to Max Amplitude"))
        self.plotChoiceBox.setItemText(2, _translate("H5Analyzer", "APDs"))
        self.plotChoiceBox.setItemText(3, _translate("H5Analyzer", "Spike Velocity"))
        self.plotChoiceBox.setItemText(4, _translate("H5Analyzer", "Spike Duration"))
        self.plotChoiceBox.setItemText(5, _translate("H5Analyzer", "Time Interval"))
        self.plotChoiceButton.setText(_translate("H5Analyzer", "Plot Choice"))
        self.saveDataButton.setText(_translate("H5Analyzer", "Save Data \n"
"in Range"))
        self.actionOpen.setText(_translate("H5Analyzer", "Open"))
        self.actionSave.setText(_translate("H5Analyzer", "Save As"))
from mplwidget import MplWidget
